# Application Properties
spring:
  application:
    name: inventory-service
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://inventory-service-database/inventory-database
    username: master
    password: m@ster@2024!!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

# Server Properties
server:
  port: 8200